apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
        - name: central-station
          image: localhost:5000/central-station:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service:9092"
            - name: ES_HOST
              value: "elasticsearch-service"
            - name: ES_PORT
              value: "9200"
            - name: ES_PASSWORD
              value: ""
            - name: BITCASK_URL
              value: "http://bitcask-server-service:8080"
          volumeMounts:
            - name: archived-data
              mountPath: /app/archivedData
      volumes:
        - name: archived-data
          emptyDir: {}
